version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: AWS_scripts/streamlit.sh
      timeout: 1200
      runas: ec2-user