version: 0.0
os: linux
files:
  - source: /
    destination: /home/app/
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: AWS_scripts/dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: AWS_scripts/start_application.sh
      runas: root