version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

hooks:
  AfterInstall:
    - location: AWS_scripts/dependencies.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: AWS_scripts/start_application.sh
      timeout: 1200
      runas: ec2-user